import localFont from "next/font/local";
import "./globals.css";
import LenisSmoothScroll from "@/components/SmoothScroll/Lenis";

const tanker = localFont({
  src: "./fonts/Tanker-Regular.woff2",
  variable: "--font-tanker",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${tanker.variable} antialiased`}
      >
        <LenisSmoothScroll />
        {children}
      </body>
    </html>
  );
}
